[tool.poetry]
name = "sekai-music-chart"
version = "0.1.0"
description = ""
authors = ["33 <moe@3-3.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
svgwrite = "^1.4.3"
cairosvg = "^2.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
